version: '3.8'
services:
  jcg_solr:
    container_name: jcg_solr
    image: solr:latest
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - jcg_example_core
volumes:
  data: